[params]
## Recover the SAME dataset with isotropic + L=2 anisotropy

fmin=4e-4
fmax=3e-3
duration=2e6
seglen=1e5
fs=0.25
Shfile=LISA_2017_PSD_M.npy
nside=1
tstart = 0
lisa_config=orbiting
tdi_lev=aet

## IMPORTANT: read the already-generated dataset
load_data=1
datafile=mldc_tdi_withnoise.txt
datatype=strain
fref = 1e-3

## Isotropic + anisotropic recovery model
model=noise+powerlaw_isgwb+powerlaw_multipole
alias={'powerlaw_isgwb':'powerlaw_isgwb',
       'powerlaw_multipole':'powerlaw_multipole'}

lmax = 2
multipole_l = 2


[inj]
## No new injection here
doInj=0


[priors]
log_Np=[-43.0,-40.0]
log_Na=[-50.0,-47.0]
alpha=[-1.0,2.5]
log_omega0=[-10.0,-5.0]
log_A_L=[-9.5,-5.5]


[run_params]
sampler=dynesty
verbose=1

## IMPORTANT: do not regenerate data
doPreProc=0

projection=E
colormap=magma
nlive=1000
Nthreads=1
FixSeed=1
seed=42

## Point this to the SAME spectrum produced by the injection run
input_spectrum=./Storage/inject_iso_plus_L2/shared_spectrum_L2.npz

checkpoint=1
checkpoint_interval=1800
sample_method=rslice

out_dir=./Storage/recover_iso_plus_L2_from_L2inj/